name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 1
  PNPM_STORE_DIR: ./.cache/pnpm

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (Node ${{ matrix.node-version }})
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Log environment variables
        run: node -e "console.log(JSON.stringify(Object.fromEntries(Object.entries(process.env).sort()), null, 2))"
      - run: pnpm test --experimental-test-coverage --test-coverage-exclude="**/__tests__/**"

  playwright:
    runs-on: ubuntu-latest
    name: Test (Playwright)
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm playwright install chromium
      - run: pnpm build:browser
      - run: pnpm test:playwright

  typescript:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - run: pnpm tsc

  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - run: pnpm eslint
