name: Setup Cypress
description: Setup Cypress with caching

runs:
  using: 'composite'
  steps:
    - name: Get Cypress version
      shell: bash
      run: |
        CYPRESS_VERSION=$(pnpm ls cypress --depth=0 --json | jq -r '.[0].devDependencies["cypress"].version')
        echo "CYPRESS_VERSION=$CYPRESS_VERSION"
        echo "CYPRESS_VERSION=$CYPRESS_VERSION" >> $GITHUB_ENV

    - name: Cache Cypress binary
      uses: actions/cache@v4
      id: cypress-cache
      with:
        path: |
          ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ env.CYPRESS_VERSION }}

    - run: pnpm exec cypress install
      shell: bash
      if: steps.cypress-cache.outputs.cache-hit != 'true'
